import ProjectDescription

let workspace = Workspace(
  name: "Blink",
  projects: [
    "Projects/App",
    "Projects/Core",
    "Projects/CommonFeature",
    "Projects/Features"
  ],
  schemes: [
    .scheme(
      name: "Release-Blink",
      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Blink")]),
      runAction: .runAction(
        configuration: .release,
        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
      ),
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    ),
    .scheme(
      name: "Dev-Blink",
      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Blink")]),
      runAction: .runAction(
        configuration: .debug,
        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
      ),
      archiveAction: .archiveAction(configuration: .debug),
      profileAction: .profileAction(configuration: .debug),
      analyzeAction: .analyzeAction(configuration: .debug)
    )
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
